[tox]
# can't install from sdist because local pyo3 repo can't be included in the sdist
skipsdist = true
envlist = py{39,310,311}

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311

[testenv]
description = Run the unit tests under {basepython}
passenv = *
deps = -r requirements-dev.txt
commands =
    pip install .
    pytest

[testenv:format]
description = Run format checker {basepython}
deps = autopep8
commands =
    autopep8 --exclude .venv  --diff --recursive --aggressive --max-line-length 120 --exit-code .

[testenv:lint-sdk]
description = Run pylint {basepython} on iota_sdk
deps =
    -r requirements-dev.txt
    pylint
commands =
    pip install .
    pylint --rcfile=.pylintrc iota_sdk/**/*.py

[testenv:lint-examples]
description = Run pylint {basepython} on examples
deps =
    -r requirements-dev.txt
    pylint
commands =
    pip install .
    pylint --rcfile=.pylintrc examples/**/*.py